services:
  - type: web
    name: game-hosting-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: COHERE_API_KEY
        sync: false
